### ISSUE TITLE
Slack Invite

### ISSUE THREAD

**Issue by atymic** [phpaustralia/codeofconduct#6]
Hi 👋 

I was wondering if the PHP australia slack is still open to join?

I tried the link: https://slack.phpaustralia.org/ but it's no longer live.

Is there any way to join?

Thanks!

cc @bendechrai

**Comment by bendechrai** [comment]
Hi @atymic. I'm no longer on the PHP Australia slack. @michaeldyrynda should be able to help you though :)

**Comment by michaeldyrynda** [comment]
I’ll be back in Australia on Tuesday. In the meantime, you can join using the [invite link](http://dyry.me/AHVvVX)!

**Comment by atymic** [comment]
Thanks for the invite link @michaeldyrynda :) Have joined.
